const app=document.getElementById('app');
const state={user:JSON.parse(localStorage.getItem('dealrush_user')||'null'),tab:'home'};
const offers=[
 {icon:'🛍️',title:'Discover a new deal',desc:'Explore a featured offer',reward:'Available'},
 {icon:'📱',title:'Try useful apps',desc:'Discover apps and services',reward:'Offer'},
 {icon:'🎁',title:'Daily bonus',desc:'Check today’s opportunity',reward:'Daily'},
 {icon:'🤝',title:'Invite friends',desc:'Share your referral link',reward:'Referral'}
];
function shell(content){app.innerHTML=`<div class="screen">${content}</div>`}
function welcome(){shell(`<div class="hero"><div class="logo">DealRush</div><div class="muted">Discover deals. Explore opportunities.</div><h1>A smarter way to discover offers.</h1><p class="muted">Create your account and get your personalized dashboard.</p><button class="btn primary" onclick="register()">Get Started</button></div><div class="container"><div class="grid"><div class="tile">🔒<b>Secure account</b><span class="small">OTP-ready authentication</span></div><div class="tile">⚡<b>Fast experience</b><span class="small">Built for mobile</span></div></div></div>`)}
function register(){shell(`<div class="top"><div class="logo">DealRush</div><p class="muted">Create your account</p></div><div class="container card"><div class="field"><label>Full name</label><input id="name" class="input" placeholder="Your name"></div><div class="field"><label>Email or phone number</label><input id="contact" class="input" placeholder="example@email.com or +234..."></div><button class="btn primary" onclick="sendOtp()">Continue with OTP</button><p class="small muted center">A real production OTP requires a configured authentication provider.</p></div>`)}
function sendOtp(){const name=document.getElementById('name').value.trim();const contact=document.getElementById('contact').value.trim();if(!name||!contact)return alert('Please enter your name and email/phone.');localStorage.setItem('pending',JSON.stringify({name,contact}));otp()}
function otp(){shell(`<div class="top"><div class="logo">DealRush</div><p class="muted">Verify your account</p></div><div class="container card"><div class="center"><div style="font-size:42px">🔐</div><h2>Enter OTP</h2><p class="muted">Enter the 6-digit code sent to your contact.</p></div><div class="field"><input id="code" maxlength="6" class="input otp" inputmode="numeric" placeholder="••••••"></div><button class="btn primary" onclick="verify()">Verify & Continue</button><p class="small center muted">Demo UI: connect Firebase/Auth provider before production use.</p></div>`)}
function verify(){const p=JSON.parse(localStorage.getItem('pending')||'null');if(!p)return register();state.user={name:p.name,contact:p.contact,balance:0,points:0,ref:'DR'+Math.random().toString(36).slice(2,8).toUpperCase()};localStorage.setItem('dealrush_user',JSON.stringify(state.user));localStorage.removeItem('pending');home()}
function home(){state.tab='home';render()}
function render(){if(!state.user)return welcome();const u=state.user;let body='';if(state.tab==='home')body=`<div class="top row between"><div><div class="small muted">Welcome back</div><h2 style="margin:4px 0">${u.name.split(' ')[0]} 👋</h2></div><div class="icon">🔔</div></div><div class="container"><div class="card balance"><div class="small">Available balance</div><div class="amount">₦${u.balance.toLocaleString()}</div><div class="row between"><span class="pill">0 points</span><button class="btn light" style="width:auto;padding:9px 13px" onclick="tab('wallet')">Wallet</button></div></div><h3 class="section">Featured</h3>${offers.slice(0,2).map(o=>offer(o)).join('')}<h3 class="section">Quick access</h3><div class="grid"><div class="tile" onclick="tab('offers')">🎁<b>Offers</b><span class="small">Explore opportunities</span></div><div class="tile" onclick="tab('ref')">👥<b>Referral</b><span class="small">Invite friends</span></div></div></div>`;
else if(state.tab==='offers')body=`<div class="top"><h2>Offers</h2><p class="muted">Explore featured opportunities.</p></div><div class="container">${offers.map(o=>offer(o,true)).join('')}<div class="card" style="margin-top:14px"><b>Sponsored offer</b><p class="small muted">Open the sponsored link to view the current offer.</p><button class="btn dark" onclick="window.open('https://omg10.com/4/11775853','_blank')">View Sponsored Offer</button></div></div>`;
else if(state.tab==='wallet')body=`<div class="top"><h2>Wallet</h2><p class="muted">Your account activity.</p></div><div class="container"><div class="card balance"><div class="small">Balance</div><div class="amount">₦${u.balance.toLocaleString()}</div><button class="btn light">Withdrawal setup</button></div><h3 class="section">Transactions</h3><div class="card center muted">No transactions yet.</div></div>`;
else if(state.tab==='ref')body=`<div class="top"><h2>Referral</h2><p class="muted">Share your invite code.</p></div><div class="container"><div class="card center"><div class="icon" style="margin:auto">🤝</div><h2>${u.ref}</h2><p class="muted">Your referral code</p><button class="btn primary" onclick="navigator.clipboard?.writeText('${u.ref}');alert('Referral code copied')">Copy Code</button></div></div>`;
else body=`<div class="top"><h2>Profile</h2><p class="muted">Account & security</p></div><div class="container"><div class="card"><b>${u.name}</b><p class="muted">${u.contact}</p><hr><p>🔐 OTP verification</p><p>🛡️ Account security</p><button class="btn light" onclick="logout()">Log out</button></div></div>`;
shell(body+`<div class="nav">${[['home','⌂','Home'],['offers','◈','Offers'],['wallet','₦','Wallet'],['ref','👥','Refer'],['profile','●','Profile']].map(x=>`<button class="${state.tab===x[0]?'active':''}" onclick="tab('${x[0]}')">${x[1]}<br>${x[2]}</button>`).join('')}</div>`)}
function offer(o){return `<div class="card" style="margin-bottom:12px"><div class="offer"><div class="icon">${o.icon}</div><div style="flex:1"><b>${o.title}</b><div class="small muted">${o.desc}</div><div class="badge">${o.reward}</div></div><button class="pill" onclick="window.open('https://omg10.com/4/11775853','_blank')">Open</button></div></div>`}
function tab(t){state.tab=t;render()} function logout(){localStorage.removeItem('dealrush_user');state.user=null;welcome()}
window.register=register;window.sendOtp=sendOtp;window.verify=verify;window.tab=tab;window.logout=logout;
state.user?render():welcome();