const app=document.getElementById('app');
const SMARTLINK='https://omg10.com/4/11775853';
const state={user:JSON.parse(localStorage.getItem('dealrush_user')||'null'),tab:'home'};
let confirmationResult=null;
let recaptchaVerifier=null;
const offers=[
 {icon:'🛍️',title:'Discover a new deal',desc:'Explore a featured offer',reward:'Available'},
 {icon:'📱',title:'Try useful apps',desc:'Discover apps and services',reward:'Offer'},
 {icon:'🎁',title:'Daily bonus',desc:'Check today’s opportunity',reward:'Daily'},
 {icon:'🤝',title:'Invite friends',desc:'Share your referral link',reward:'Referral'}
];
function shell(content){app.innerHTML=`<div class="screen">${content}</div>`}
function welcome(){shell(`<div class="hero"><div class="logo">DealRush</div><div class="muted">Discover deals. Explore opportunities.</div><h1>A smarter way to discover offers.</h1><p class="muted">Create your account with secure phone verification.</p><button class="btn primary" onclick="register()">Get Started</button></div><div class="container"><div class="grid"><div class="tile">🔒<b>Secure account</b><span class="small">Firebase phone OTP</span></div><div class="tile">⚡<b>Fast experience</b><span class="small">Built for mobile</span></div></div></div>`)}
function register(){shell(`<div class="top"><div class="logo">DealRush</div><p class="muted">Create your account</p></div><div class="container card"><div class="field"><label>Full name</label><input id="name" class="input" placeholder="Your name" autocomplete="name"></div><div class="field"><label>Phone number</label><input id="phone" class="input" placeholder="+2348012345678" inputmode="tel" autocomplete="tel"></div><div id="recaptcha-container"></div><button id="send-btn" class="btn primary" onclick="sendOtp()">Send OTP</button><p id="status" class="small muted center">Use international format, e.g. +2348012345678.</p></div>`);setTimeout(initRecaptcha,100)}
function initRecaptcha(){try{if(recaptchaVerifier)recaptchaVerifier.clear();recaptchaVerifier=new firebase.auth.RecaptchaVerifier('recaptcha-container',{size:'normal',callback:()=>{document.getElementById('status').textContent='Verification complete. Tap Send OTP.'},'expired-callback':()=>{document.getElementById('status').textContent='Verification expired. Please complete it again.'}});recaptchaVerifier.render()}catch(e){console.error(e);document.getElementById('status').textContent='Could not load security verification. Refresh and try again.'}}
function normalizePhone(v){return v.replace(/[\s()-]/g,'')}
async function sendOtp(){const name=document.getElementById('name').value.trim();const phone=normalizePhone(document.getElementById('phone').value.trim());const status=document.getElementById('status');if(!name||!phone)return alert('Please enter your name and phone number.');if(!/^\+[1-9]\d{7,14}$/.test(phone))return alert('Enter the phone number in international format, e.g. +2348012345678.');if(!recaptchaVerifier)return alert('Please wait for the security verification to load.');status.textContent='Sending OTP…';try{confirmationResult=await firebase.auth().signInWithPhoneNumber(phone,recaptchaVerifier);localStorage.setItem('pending_name',name);localStorage.setItem('pending_phone',phone);otp()}catch(error){console.error(error);status.textContent='Could not send OTP.';alert('OTP failed: '+friendlyError(error));try{const w=await recaptchaVerifier.render();grecaptcha.reset(w)}catch(_){}}}
function otp(){shell(`<div class="top"><div class="logo">DealRush</div><p class="muted">Verify your phone</p></div><div class="container card"><div class="center"><div style="font-size:42px">🔐</div><h2>Enter OTP</h2><p class="muted">A 6-digit code was sent by SMS.</p></div><div class="field"><input id="code" maxlength="6" class="input otp" inputmode="numeric" placeholder="••••••" autocomplete="one-time-code"></div><button class="btn primary" onclick="verify()">Verify & Continue</button><button class="btn light" onclick="register()">Change number</button><p id="otp-status" class="small center muted"></p></div>`)}
async function verify(){const code=document.getElementById('code').value.trim();const status=document.getElementById('otp-status');if(!/^\d{6}$/.test(code))return alert('Enter the 6-digit OTP.');if(!confirmationResult)return register();status.textContent='Verifying…';try{const result=await confirmationResult.confirm(code);const name=localStorage.getItem('pending_name')||'User';const phone=localStorage.getItem('pending_phone')||result.user.phoneNumber;state.user={uid:result.user.uid,name,contact:phone,balance:0,points:0,ref:'DR'+Math.random().toString(36).slice(2,8).toUpperCase()};localStorage.setItem('dealrush_user',JSON.stringify(state.user));localStorage.removeItem('pending_name');localStorage.removeItem('pending_phone');confirmationResult=null;home()}catch(error){console.error(error);status.textContent=friendlyError(error);}}
function friendlyError(e){const c=e&&e.code||'';if(c.includes('invalid-verification-code'))return'Incorrect OTP. Check the SMS and try again.';if(c.includes('too-many-requests'))return'Too many attempts. Please wait and try again later.';if(c.includes('quota-exceeded'))return'SMS quota has been reached for this Firebase project.';if(c.includes('unauthorized-domain'))return'This website domain is not authorized in Firebase Authentication.';if(c.includes('captcha-check-failed'))return'reCAPTCHA failed. Please refresh and try again.';return e&&e.message?e.message:'Something went wrong.'}
function home(){state.tab='home';render()}
function render(){if(!state.user)return welcome();const u=state.user;let body='';if(state.tab==='home')body=`<div class="top row between"><div><div class="small muted">Welcome back</div><h2 style="margin:4px 0">${escapeHtml(u.name.split(' ')[0])} 👋</h2></div><div class="icon">🔔</div></div><div class="container"><div class="card balance"><div class="small">Available balance</div><div class="amount">₦${Number(u.balance||0).toLocaleString()}</div><div class="row between"><span class="pill">${u.points||0} points</span><button class="btn light smallbtn" onclick="tab('wallet')">Wallet</button></div></div><h3 class="section">Featured</h3>${offers.slice(0,2).map(o=>offer(o)).join('')}<h3 class="section">Quick access</h3><div class="grid"><div class="tile" onclick="tab('offers')">🎁<b>Offers</b><span class="small">Explore opportunities</span></div><div class="tile" onclick="tab('ref')">👥<b>Referral</b><span class="small">Invite friends</span></div></div></div>`;else if(state.tab==='offers')body=`<div class="top"><h2>Offers</h2><p class="muted">Explore featured opportunities.</p></div><div class="container">${offers.map(o=>offer(o)).join('')}<div class="card sponsor"><b>Sponsored offer</b><p class="small muted">Open the sponsored link to view the current offer.</p><button class="btn dark" onclick="openOffer()">View Sponsored Offer</button></div></div>`;else if(state.tab==='wallet')body=`<div class="top"><h2>Wallet</h2><p class="muted">Your account activity.</p></div><div class="container"><div class="card balance"><div class="small">Balance</div><div class="amount">₦${Number(u.balance||0).toLocaleString()}</div><button class="btn light">Withdrawal setup</button></div><h3 class="section">Transactions</h3><div class="card center muted">No transactions yet.</div></div>`;else if(state.tab==='ref')body=`<div class="top"><h2>Referral</h2><p class="muted">Share your invite code.</p></div><div class="container"><div class="card center"><div class="icon">🤝</div><h2>${escapeHtml(u.ref)}</h2><p class="muted">Your referral code</p><button class="btn primary" onclick="copyRef()">Copy Code</button></div></div>`;else body=`<div class="top"><h2>Profile</h2><p class="muted">Account & security</p></div><div class="container"><div class="card"><b>${escapeHtml(u.name)}</b><p class="muted">${escapeHtml(u.contact)}</p><hr><p>🔐 Firebase phone verification</p><p>🛡️ Account security</p><button class="btn light" onclick="logout()">Log out</button></div></div>`;shell(body+`<div class="nav">${[['home','⌂','Home'],['offers','◈','Offers'],['wallet','₦','Wallet'],['ref','👥','Refer'],['profile','●','Profile']].map(x=>`<button class="${state.tab===x[0]?'active':''}" onclick="tab('${x[0]}')">${x[1]}<br>${x[2]}</button>`).join('')}</div>`)}
function offer(o){return `<div class="card" style="margin-bottom:12px"><div class="offer"><div class="icon">${o.icon}</div><div style="flex:1"><b>${o.title}</b><div class="small muted">${o.desc}</div><div class="badge">${o.reward}</div></div><button class="pill" onclick="openOffer()">Open</button></div></div>`}
function openOffer(){window.open(SMARTLINK,'_blank','noopener,noreferrer')}
function copyRef(){navigator.clipboard?.writeText(state.user.ref);alert('Referral code copied')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function tab(t){state.tab=t;render()} 
async function logout(){try{await firebase.auth().signOut()}catch(e){}localStorage.removeItem('dealrush_user');state.user=null;welcome()}
window.register=register;window.sendOtp=sendOtp;window.verify=verify;window.tab=tab;window.logout=logout;window.openOffer=openOffer;window.copyRef=copyRef;
firebase.auth().onAuthStateChanged(user=>{if(user&&state.user){render()}else if(!user&&!state.user){welcome()}});
state.user?render():welcome();
